version: '3.5'
services:
    example-mysql:
        image: mysql:latest
        container_name: "example-mysql"
        volumes:
            - "./docker/data/db:/var/lib/mysql"
        restart: always
        ports:
            - "3523:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: example
        networks:
            - example-network
    example-phpfpm:
        image: chrsc/php-fpm-laravel:latest
        container_name: "example-phpfpm"
        depends_on:
            - example-mysql
        volumes:
            - "./:/var/www/"
            - "./docker/config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
        restart: always
        networks:
            - example-network
    example-nginx:
        image: nginx:1.17-alpine
        container_name: "example-nginx"
        depends_on:
            - example-phpfpm
        ports:
            - "8580:80"
            - "8543:443"
        volumes:
            - "./:/var/www/"
            - "./docker/config/default.conf:/etc/nginx/conf.d/default.conf"
            - "./docker/certs:/etc/nginx/certs"
            - "./docker/logs/nginx:/var/log/nginx"
        restart: always
        networks:
            - example-network
    example-redis:
        image: redis:5.0.6-alpine
        container_name: "example-redis"
        depends_on:
            - example-phpfpm
        volumes:
            - "./docker/data/redis:/data"
            - "./docker/config/redis.conf:/usr/local/etc/redis/redis.conf"
        restart: always
        networks:
            - example-network
networks:
    example-network:
        name: custom-example-network
